version: "3.9"

networks:
  dev_env:
    driver: bridge

services:
  asset-manager-db:
    image: debezium/postgres:10
    container_name: asset-manager-db
    networks:
      - dev_env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
  asset-manager-php:
    container_name: asset-manager-php
    build:
      context: ./manifests
    ports:
      - '9000:9000'
    volumes:
      - ../asset-manager/:/var/www/asset-manager
    depends_on:
      - asset-manager-db
    networks:
      - dev_env
  asset-manager-nginx:
    container_name: asset-manager-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../asset-manager/:/var/www/asset-manager
      - ./manifests/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - asset-manager-php
      - asset-manager-db
    networks:
      - dev_env